### ISSUE TITLE
Contribute a Pixel to the Canvas

### ISSUE THREAD

**Issue by dkundel** [twilio-labs/open-pixel-art#1]
We want to have as many people as possible contribute a pixel to the canvas on [open-pixel-art.com](https://open-pixel-art.com) and teach people how to contribute to open source along the way.

## How do I contribute a pixel?

In order to contribute a pixel, you'll have to contribute an entry to the `_data/pixels.json` file. You can pick your favorite color and your preferred coordinates on the canvas.

You can find the exact instructions in the [Contributing Guide](https://github.com/twilio-labs/open-pixel-art/blob/master/CONTRIBUTING.md).

## I'm new to open source. How do I contribute?

If you are new to contributing to open-source, check out our mission inside [TwilioQuest](https://twil.io/hacktoberfest-quest) that will guide you through every step of contributing to this project.

**Comment by Prathamesh404** [comment]
Are the pixels limited to 39x39?

**Comment by dkundel** [comment]
Right now they are. But we'll increase the canvas size soon!

**Comment by beardys** [comment]
this problem occurring and many people are finding it frustrating,
the problem seems to be the that - when the script is checking the entries it ignore all of the entries after your change and then reports that they are missing. 
This need to sorted as a Twilio champion I stream this live and its is difficult to encourage use of Twilio quest when problems like this go unsolved for a long period of time like this has done for over 6 months

**Comment by Pratham-R** [comment]
feat(pixels): added my new pixel(38,48) #4817
