### ISSUE TITLE
TwilioQuest AppImage fails to run on Kali Linux

### ISSUE THREAD

**Issue by vinc456** [twilio-labs/open-pixel-art#1312]
I was not able to run TwilioQuest AppImage on Kali Linux. 

```
5.2.0-kali3-amd64
Distributor ID:	Kali
Description:	Kali GNU/Linux Rolling
Release:	2019.4
Codename:	kali-rolling

```

I'm not very familiar with AppImage but I did change the executable bit and tried to run the file, only to encounter the following error.

> ./TwilioQuest.AppImage 
> [28482:1019/054935.507976:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /tmp/.mount_TwiliozhGxvg/chrome-sandbox is owned by root and has mode 4755.
> Trace/breakpoint trap
> 

> $ ./TwilioQuest.AppImage 
> [28889:1019/055402.790344:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /tmp/.mount_TwiliorD2I5Z/chrome-sandbox is owned by root and has mode 4755.
> 

Didn't investigate further, hopefully PEBKAC.

**Comment by kwhinnery** [comment]
Hm, a quick google search of the error seems to indicate that there are permissions issues at play - check this comment:

https://github.com/electron/electron/issues/17972#issuecomment-487369441

A suggestion within is to execute the AppImage with the `--no-sandbox` option - would be worth a shot I think? Otherwise, changing ownership and permissions of the AppImage file may help. Sorry, TBH I am still a bit of a n00b when it comes to Linux + Electron.
