### ISSUE TITLE
[BUG] CI is failing due to wrong diff comparison in Danger

### ISSUE THREAD

**Issue by dkundel** [twilio-labs/open-pixel-art#2046]
## Description
Right now the CI is failing on basically every run because it complains that people removed pixels from others. It appears to be because it's using the wrong diff for the check.

## Expected Behavior
PRs like this one should succeed: https://github.com/twilio-labs/open-pixel-art/pull/2045

## Actual Behavior
PR failed because it's claiming it removed additional pixels https://github.com/twilio-labs/open-pixel-art/pull/2045/checks?check_run_id=589878945

## Possible Fix
The diff that's being generated by Danger seems to be wrong. I did some digging but couldn't figure out yet how to get the merge commit instead. [I asked on Spectrum](https://spectrum.chat/danger/general/how-do-i-run-danger-against-the-merge-commit~10ed5739-4f7d-4394-8119-9330d2cf23b6) but haven't heard back yet. Next step would probably be to report a bug on [danger/danger-js](https://github.com/danger/danger-js). 

## Steps to Reproduce

1. Check the changes in this PR: https://github.com/twilio-labs/open-pixel-art/pull/2045/files
2. There is clearly only one line added
3. Check the Danger logs of https://github.com/twilio-labs/open-pixel-art/pull/2045/checks?check_run_id=589878945
4. It says it failed because pixels were removed.

## Context
This is currently blocking the automatic PR experience for users.

**Comment by tesla809** [comment]
having similar problems with my PR #2158

**Comment by jaredcacurak** [comment]
Hi @dkundel, this behavior was introduced when `danger-js` changed its JSON patch implementation to `fast-json-patch`.  danger/danger-js/pull/1019

The output from `fast-json-patch`'s `compare` function does not align with the the [RFC-6902 - JavaScript Object Notation (JSON) Patch](https://tools.ietf.org/html/rfc6902#appendix-A.2).

> A.2.  Adding an Array Element
>
>   An example target JSON document:
>
>   `{ "foo": [ "bar", "baz" ] }`
>
>   A JSON Patch document:
>
>  ` [
>     { "op": "add", "path": "/foo/1", "value": "qux" }
>   ]`
>
>   The resulting JSON document:
>
>   `{ "foo": [ "bar", "qux", "baz" ] }`


In this example we see `fast-json-patch` returns a superfluous `replace` operation along with the expected `add` operation.

```js
var fastJsonPatch = require("fast-json-patch");

let v1 = { "foo": [ "bar", "baz" ] }
let v2 = { "foo": [ "bar", "qux", "baz" ] }

fastJsonPatch.compare(v1, v2);

// [Object {op: "replace", path: "/foo/1", value: "qux"}, Object {op: "add", path: "/foo/2", value: "baz"}]
```
I wonder if `open-pixel-art`'s danger file should attempt to [squash the verbose patch](https://github.com/Starcounter-Jack/JSON-Patch/issues/204#issuecomment-394110124), or propose `danger-js` use another JSON patch implementation?

**Comment by dkundel** [comment]
That's a good catch! I think we should see if we can change it in the Dangerfile. I was actually the one who introduced the change on the danger side since the previous implementation and others that I could find weren't very memory efficient and would cause memory leaks during the diffing.

**Comment by jharkins81** [comment]
Even with it failing peeps that want that sweet sweet hoodie can still use their pull request number in the dialog box =)

**Comment by madscientist001** [comment]
Sharing some simple steps here that I used as a workaround for the bug:
Step 1 : Set upstream as the remote master branch of the original repository owned by twilio-labs.
`git remote add upstream https://github.com/twilio-labs/open-pixel-art.git`
Step 2 : Checkout your local branch and merge upstream changes with your local branch.
`git checkout {your_branch}`
`git pull upstream master`
Step 3 : Update your remote branch.
`git push origin {your_branch}`

This should trigger the automatic review process again and since your branch is not behind the upstream master, it should pass all the checks and get merged automatically by the mergify bot.

**Note: In the unlikely event where a commit gets merged into upstream master before you have completed the above steps, your branch will again be a certain number of commits behind the upstream master and you might have to redo the process.**
