### ISSUE TITLE
[BUG] Username with uppercase can't do the step : Open a Pull Request

### ISSUE THREAD

**Issue by Reloadaxe** [twilio-labs/open-pixel-art#2271]
## Description
When i put my PR number (#2270) in the game, it said : "We found the Pull Request #2270 on the Open Pixel Art remote repository, but it doesn't belong to your GitHub user "reloadaxe"!"

## Expected Behavior
Success

## Actual Behavior
Failed

**Comment by rmkubik** [comment]
TwilioQuest expects you to match your username exactly, including case sensitivity. Make sure your GitHub username inside of TwilioQuest is `Realoadaxe` with a capital `R` like it is here. You can update your environment variables inside TwilioQuest by going to `Settings > Environment`, clicking `UNLOCK`, and then finding `TQ_GITHUB_USERNAME` and updating the value.

---

Depending on what version you were playing in, you may've hit a bug that was lowercasing usernames upon checking for PRs.

That bug should be fixed in `3.1.27`.
